'use client'
import { useMemo,useState } from 'react'
import Link from 'next/link'
import { useApp } from '@/components/AppContext'
import { Button,Dialog,Input,EmptyState,LoadingState,ErrorState } from '@/components/ui'
import Icon from '@/components/Icon'
import { useTasks } from './TasksContext'
import TaskEditor from './TaskEditor'
import TaskRow from './TaskRow'
import { todayInZone } from '@/lib/dates'
export default function TasksPage(){
 const {t,user,settings,language,notify}=useApp(),{tasks,folders,loading,error,reload,saveFolder,deleteFolder}=useTasks()
 const [filter,setFilter]=useState('active'),[folder,setFolder]=useState('all'),[search,setSearch]=useState(''),[editing,setEditing]=useState(null),[folderEdit,setFolderEdit]=useState(null),[folderBusy,setFolderBusy]=useState(false),[folderError,setFolderError]=useState(''),[deleteConfirm,setDeleteConfirm]=useState(false)
 const today=todayInZone(settings.timezone),active=tasks.filter(x=>!x.completed),done=tasks.filter(x=>x.completed).length
 const visible=useMemo(()=>tasks.filter(x=>(filter==='all'||(filter==='completed'?x.completed:filter==='today'?!x.completed&&x.due_date?.slice(0,10)===today:filter==='upcoming'?!x.completed&&x.due_date?.slice(0,10)>today:!x.completed))&&(folder==='all'||(folder==='none'?!x.folder_id:x.folder_id===Number(folder)))&&x.title.toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>Number(a.completed)-Number(b.completed)||(a.due_date||'9999').localeCompare(b.due_date||'9999')||({high:0,medium:1,low:2}[a.priority]-{high:0,medium:1,low:2}[b.priority])),[tasks,filter,folder,search,today])
 const overdue=visible.filter(x=>!x.completed&&x.due_date&&x.due_date.slice(0,10)<today),regular=visible.filter(x=>!overdue.includes(x))
 async function submitFolder(e){e.preventDefault();setFolderBusy(true);setFolderError('');try{await saveFolder(folderEdit);setFolderEdit(null);notify(t('Папка сохранена','Folder saved'))}catch{setFolderError(t('Не удалось сохранить папку','Could not save folder'))}finally{setFolderBusy(false)}}
 async function removeFolder(){setFolderBusy(true);try{await deleteFolder(folderEdit.id);setFolder('all');setFolderEdit(null);setDeleteConfirm(false)}catch{setFolderError(t('Не удалось удалить папку','Could not delete folder'))}finally{setFolderBusy(false)}}
 return <div className="page tasks-page"><header className="page-header"><div><p className="eyebrow">{new Intl.DateTimeFormat(language==='ru'?'ru-RU':'en-US',{weekday:'long',day:'numeric',month:'long',timeZone:settings.timezone}).format(new Date())}</p><h1>{t('Сделайте место важному.','Make room for what matters.')}</h1><p className="page-subtitle">{t('Хороший день начинается с ясного плана.','A good day starts with a clear plan.')}</p></div><Button variant="primary" onClick={()=>setEditing({folder_id:!['all','none'].includes(folder)?Number(folder):null})}><Icon name="plus"/>{t('Новая задача','New task')}</Button></header>
 <div className="overview-grid"><button className={`overview-card ${filter==='today'?'selected':''}`} onClick={()=>setFilter('today')}><span className="stat-icon blue"><Icon name="sun"/></span><span className="stat-number">{active.filter(x=>x.due_date?.slice(0,10)===today).length}</span><span className="stat-label">{t('На сегодня','Today')}</span><span className="stat-hint">{t('Сфокусируйтесь на главном','Focus on what matters')}</span></button><button className={`overview-card ${filter==='upcoming'?'selected':''}`} onClick={()=>setFilter('upcoming')}><span className="stat-icon purple"><Icon name="calendar"/></span><span className="stat-number">{active.filter(x=>x.due_date?.slice(0,10)>today).length}</span><span className="stat-label">{t('Впереди','Upcoming')}</span><span className="stat-hint">{t('Всё в своё время','Everything in its own time')}</span></button><button className={`overview-card ${filter==='completed'?'selected':''}`} onClick={()=>setFilter('completed')}><span className="stat-icon green"><Icon name="check"/></span><span className="stat-number">{done}</span><span className="stat-label">{t('Завершено','Completed')}</span><span className="stat-hint">{t('Каждый шаг имеет значение','Every step counts')}</span></button></div>
 <div className="workspace-grid"><section className="task-panel panel"><div className="panel-heading"><h2>{t('Мои задачи','My tasks')} <span className="count-badge">{visible.length}</span></h2><label className="search-input"><Icon name="search" size={17}/><input aria-label={t('Поиск задач','Search tasks')} placeholder={t('Найти задачу','Search tasks')} value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="task-toolbar"><div className="segmented" aria-label={t('Фильтр задач','Task filter')}>{[['active','Активные','Active'],['all','Все','All'],['completed','Выполненные','Completed']].map(([key,ru,en])=><button key={key} aria-pressed={filter===key} className={filter===key?'selected':''} onClick={()=>setFilter(key)}>{t(ru,en)}</button>)}</div><select className="input folder-select" value={folder} onChange={e=>setFolder(e.target.value)} aria-label={t('Папка задач','Task folder')}><option value="all">{t('Все папки','All folders')}</option><option value="none">{t('Без папки','No folder')}</option>{folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></div>
 {loading?<LoadingState/>:error?<ErrorState error={error} onRetry={reload} t={t}/>:!visible.length?<EmptyState title={search?t('Ничего не найдено','No results'):t('Здесь пока тихо','A little space to begin')} description={search?t('Попробуйте другой запрос или фильтр.','Try another search or filter.'):t('Добавьте первую задачу. Остальное — шаг за шагом.','Add your first task. Take the rest one step at a time.')}><Button onClick={()=>setEditing({})}><Icon name="plus"/>{t('Добавить задачу','Add task')}</Button></EmptyState>:<>{overdue.length>0&&<><div className="list-group-label danger-text">{t('Требуют внимания','Needs attention')}<span>{overdue.length}</span></div>{overdue.map(task=><TaskRow key={task.id} task={task} onEdit={setEditing}/>)}</>}{regular.length>0&&<><div className="list-group-label">{filter==='today'?t('Сегодня','Today'):filter==='upcoming'?t('Запланировано','Scheduled'):t('Ваш план','Your plan')}<span>{regular.length}</span></div>{regular.map(task=><TaskRow key={task.id} task={task} onEdit={setEditing}/>)}</>}</>}
 <button className="add-task-inline" onClick={()=>setEditing({folder_id:!['all','none'].includes(folder)?Number(folder):null})}><Icon name="plus" size={18}/>{t('Добавить задачу','Add task')}</button></section>
 <aside className="task-aside"><section className="panel folder-panel"><div className="panel-heading"><h2>{t('Папки','Folders')}</h2><Button variant="ghost" aria-label={t('Создать папку','Create folder')} onClick={()=>{setFolderEdit({name:'',color:'#007aff'});setFolderError('');setDeleteConfirm(false)}}><Icon name="plus" size={18}/></Button></div>{folders.map(f=><div className="folder-row" key={f.id}><button onClick={()=>setFolder(String(f.id))}><span className="folder-color" style={{color:f.color}}><Icon name="folder" size={18}/></span><span>{f.name}</span><small>{tasks.filter(x=>x.folder_id===f.id&&!x.completed).length}</small></button><button className="icon-button" aria-label={`${t('Изменить папку','Edit folder')}: ${f.name}`} onClick={()=>{setFolderEdit(f);setFolderError('');setDeleteConfirm(false)}}><Icon name="more" size={16}/></button></div>)}{!folders.length&&<p className="aside-hint">{t('Разделите задачи по проектам или сферам жизни.','Organize tasks by project or area of your life.')}</p>}</section><section className="gentle-card"><span className="gentle-label">CHRONICLE / {t('ПРИНЦИП 01','PRINCIPLE 01')}</span><Icon name="leaf" size={32}/><h3>{t('Не всё сразу.','One thing at a time.')}<br/>{t('По одному шагу.','At your own pace.')}</h3><p>{t('Оставьте место для жизни между пунктами списка.','Leave a little room for life between the checkboxes.')}</p><Link href="/app/challenges">{t('Начать челлендж','Start a challenge')}<Icon name="arrow" size={16}/></Link></section><p className="aside-footer">{t('Меньше шума. Больше ясности.','Less noise. More clarity.')}</p></aside></div>
 {editing&&<TaskEditor key={editing.id||'new'} task={editing} onClose={()=>setEditing(null)}/>}<Dialog open={!!folderEdit} title={folderEdit?.id?t('Изменить папку','Edit folder'):t('Новая папка','New folder')} onClose={()=>!folderBusy&&setFolderEdit(null)}>{folderEdit&&<form className="stack" onSubmit={submitFolder}><label className="field">{t('Название папки','Folder name')}<Input autoFocus required maxLength={100} value={folderEdit.name} onChange={e=>setFolderEdit({...folderEdit,name:e.target.value})}/></label><label className="field">{t('Цвет','Color')}<Input type="color" value={folderEdit.color||'#007aff'} onChange={e=>setFolderEdit({...folderEdit,color:e.target.value})}/></label>{folderError&&<p role="alert" className="form-error">{folderError}</p>}<div className="dialog-actions">{folderEdit.id&&<Button variant="danger" onClick={()=>setDeleteConfirm(true)}>{t('Удалить папку','Delete folder')}</Button>}<Button type="submit" variant="primary" disabled={folderBusy}>{t('Сохранить','Save')}</Button></div>{deleteConfirm&&<div className="delete-confirm"><p>{t('Задачи сохранятся в разделе «Без папки». Удалить папку?','Tasks will remain in No folder. Delete this folder?')}</p><Button variant="danger" disabled={folderBusy} onClick={removeFolder}>{t('Подтвердить удаление','Confirm deletion')}</Button></div>}</form>}</Dialog></div>
}
